{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}-kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: {{ include "microservice.name" . }}-kafka
{{- end }}

