{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "microservice.name" . }}-postgres
{{- end }}

