{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "microservice.fullname" . }}-postgres
spec:
  serviceName: {{ include "microservice.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "microservice.name" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "microservice.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "microservice.fullname" . }}
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
{{- end }}

