apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    app: {{ include "microservice.name" . }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  KAFKA_PASSWORD: {{ .Values.kafka.password | b64enc | quote }}

