name: Review

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  codex_review:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Run Codex Review
      uses: your-org/codex-review-action@v1
