name: Review

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  codex-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run review with Codex
      uses: ./.github/actions/codex-review-action
      with:
        openai_api_key: ${{ secrets.OPENAI_API_KEY }}
